refactor `role channel addall` command
ungdev/EtuUTT-Discord-Bot pull request #10
Opened 2024-03-22 14:24 UTC by imperosol

- Utilise la fonction `split_msg`  dans la commande pour gérer un peu mieux le retour utilisateur
- groupe le résultat en trois catégories (salons déjà existants, noms de rôles sans catégorie correspondante, salons effectivement créés) et les présente de la même manière que la commande `role lessthan`
- Ajoute la fonction utilitaire `create_ue_channel`, qui crée un salon textuel d'UE

Exemple : 
![image](https://github.com/ungdev/EtuUTT-Discord-Bot/assets/56346771/43bb2b6f-8633-480c-9923-2623f9dc2de5)

2024-03-27 17:10 UTC, Zalk0 requested changes
https://peps.python.org/pep-0420/
On veut un namespace package non ?
Pas besoin de \_\_init__.py

2024-03-28 09:19 UTC, imperosol commented
Pourquoi tu veux un namespace package ? Selon la [doc](https://docs.python.org/3/glossary.html#term-namespace-package), un namespace package est :

> A [PEP 420](https://peps.python.org/pep-0420/) [package](https://docs.python.org/3/glossary.html#term-package) which serves only as a container for subpackages.

C'est une manière de permettre une configuration plus avancée, dans des cas cas qui ne correspondent clairement aux besoins du bot.

Toujours selon la [doc ](https://docs.python.org/3/tutorial/modules.html#packages): 

> The \_\_init\_\_.py files are required to make Python treat directories containing the file as packages (unless using a [namespace package](https://docs.python.org/3/glossary.html#term-namespace-package), a relatively advanced feature). This prevents directories with a common name, such as string, from unintentionally hiding valid modules that occur later on the module search path.

Pour un usage basique, on ne voit pas la différence entre un package normal et un namespace package, mais c'est sémantiquement deux choses bien différentes. Et en l'occurrence, ce qu'on voudrait ici, c'est plutôt des packages traditionnels.

2024-03-28 09:24 UTC, imperosol commented on pyproject.toml
> +select = ["E", "F", "I", "UP", "B", "RET", "SIM", "PT", "RUF", "T"]
Mais T tout seul, c'est uniquement les règles flake8-print

2024-03-28 09:31 UTC, imperosol commented on etuutt_bot/types.py
> +ChannelId = NewType("ChannelId", int)
C'est uniquement du refactor. En travaillant sur un code qui appelait `parse_categories`, qui renvoie `dict[str, int]`, je me suis rendu que je ne savais pas à quoi correspondait l'int. Le nombre de rôles ? Le nombre de salons ? L'id de la catégorie sur discord ? L'id de la catégorie dans un autre référentiel ? Bon, c'est l'id Discord de la catégorie, mais j'ai dû plonger dans la fonction pour m'en souvenir.

Si ça m'a demandé cette réflexion, ça veut dire que le type en lui-même ne donne pas assez d'informations sur ce qu'on attend. Et comme c'est pas l'objet de la PR, j'ai refactor cette partie sans en changer le comportement. 

D'où le NewType :

> A NewType is considered a distinct type by a typechecker. At runtime, however, calling a NewType returns its argument unchanged.

2024-03-28 10:27 UTC, Zalk0 commented on etuutt_bot/types.py
> +ChannelId = NewType("ChannelId", int)
Tout de façon je vais le redégager derrière (on aura plus besoin des fonctions parse ou du moins pas comme ça) mais sinon tes changements sont good

2024-03-28 10:28 UTC, Zalk0 approved these changes
ça me semble bon maintenant

2024-03-28 10:29 UTC, merged